name: Kubernetes with Helm Rick and Morty Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
          
      - name: Set up minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Git Clone
        uses: actions/checkout@v4

      - name: Deploy to Minikube
        run: |
           cd Step5
           helm install rick-morty-api . --values values.yaml 

      - name: Wait for deployment to be ready
        run: kubectl rollout status deployment/rick-and-morty-deployment

      - name: Get Service URL
        id: service-url
        run: echo "::set-output name=url::$(minikube service rick-and-morty-service --url)"

      - name: Get Target Port
        id: target-port
        run: |
          URL=${{ steps.service-url.outputs.url }}
          TARGET_PORT=$(echo $URL | awk -F':' '{print $3}')
          echo "::set-output name=target_port::$TARGET_PORT"

      - name: Run tests
        run: |
          MINIKUBE_IP=$(minikube ip)
          TARGET_PORT=${{ steps.target-port.outputs.target_port }}
          curl  http://$MINIKUBE_IP:$TARGET_PORT/healthcheck
          curl  http://$MINIKUBE_IP:$TARGET_PORT/characters